### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: clojure/data/xml/node/Element

### ISSUE THREAD

**Issue by gaberger** [luchiniatwork/cambada#1]
This is such a cool project.. Thanks for working on this.. I am executing ```clj -R:cambada -m cambada.uberjar```

Getting the following exception.
```
Cleaning target
Creating target/classes
  Compiling inject-github-id.core
Creating target/inject_github_id-1.0.0-SNAPSHOT.jar
Updating pom.xml
Exception in thread "main" java.lang.NoClassDefFoundError: clojure/data/xml/node/Element
	at cambada.jar$parse_xml$fn__2572.invoke(jar.clj:194)
	at clojure.core$filter$fn__5614.invoke(core.clj:2813)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.LazySeq.first(LazySeq.java:71)
	at clojure.lang.RT.first(RT.java:685)
	at clojure.core$first__5106.invokeStatic(core.clj:55)
	at clojure.core$first__5106.invoke(core.clj:55)
	at cambada.jar$parse_xml.invokeStatic(jar.clj:194)
	at cambada.jar$parse_xml.invoke(jar.clj:190)
	at cambada.jar$sync_pom$fn__2580.invoke(jar.clj:230)
	at cambada.jar$sync_pom.invokeStatic(jar.clj:227)
	at cambada.jar$sync_pom.invoke(jar.clj:222)
	at cambada.jar$apply_BANG_.invokeStatic(jar.clj:237)
	at cambada.jar$apply_BANG_.invoke(jar.clj:233)
	at cambada.uberjar$apply_BANG_.invokeStatic(uberjar.clj:130)
	at cambada.uberjar$apply_BANG_.invoke(uberjar.clj:129)
	at cambada.cli$runner.invokeStatic(cli.clj:120)
	at cambada.cli$runner.invoke(cli.clj:115)
	at cambada.uberjar$_main.invokeStatic(uberjar.clj:142)
	at cambada.uberjar$_main.doInvoke(uberjar.clj:140)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.main$main_opt.invokeStatic(main.clj:317)
	at clojure.main$main_opt.invoke(main.clj:313)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: java.lang.ClassNotFoundException: clojure.data.xml.node.Element
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 33 more
```

**Comment by jwhitlark** [comment]
Yea, me too.

**Comment by orestis** [comment]
I think this is now resolved, I see the xml dependency in deps.edn and pom.xml

**Comment by luchiniatwork** [comment]
This seems to be resolved. Closing the ticket for now. Let me know if it wasn't resolved for some reason.
