### ISSUE TITLE
ERROR! Error: Main entry point class not found.

### ISSUE THREAD

**Issue by zilti** [luchiniatwork/cambada#29]
```
com.oracle.svm.core.util.UserError$UserException: Main entry point class 'cvfetcher.fetch-linkedin' not found.
        at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:260)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:448)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:113)
Error: Image build request failed with exit status 1
```

This happens when I try to compile a native image.

**Comment by mattsfrey** [comment]
Also getting this trying to compile the fulcro 3 template app (https://github.com/fulcrologic/fulcro-template)

```
ERROR! Error: Main entry point class 'app.server-main' not found.
com.oracle.svm.core.util.UserError$UserException: Main entry point class 'app.server-main' not found.
```
